### ISSUE TITLE
Multiple METHOD: definitions in the calendar ->ValueError: A VCALENDAR must have at most one METHOD

### ISSUE THREAD

**Issue by DominiqueMeus** [collective/icalendar#286] opened 2019-02-07 16:34 UTC
The calendar I am importing has the METHOD: tag defined twice like this:
METHOD:PUBLISH
...
METHOD:PUBLISH

This gives:
`  File "<redacted>/file.py", line 15, in <module>
    objectCalendar1 = Calendar(rawCalendar)
  File "C:\Program Files (x86)\Python\lib\site-packages\ics\icalendar.py", line 69, in __init__
    self._populate(container[0])  # Use first calendar
  File "C:\Program Files (x86)\Python\lib\site-packages\ics\component.py", line 57, in _populate
    .format(container.name, extractor.type))
ValueError: A VCALENDAR must have at most one METHOD`

You can get around it by filtering out the double entry out of the string and only then turn it into a Calendar. However, perhaps iCalendar should only consider the first Method tag and ignore the rest?
Ideally the creator of ics calendars don't use redundant tags but that is out of my control.

**Comment by natashamm** [comment] 2024-05-19 17:26
From [RFC 5545](https://www.ietf.org/rfc/rfc5545.txt)
```
   Property Name:  METHOD
...
   Conformance:  This property can be specified once in an iCalendar
      object.
```
If a calendar has more than 1 `METHOD`s then it is not RFC 5545 compliant, so I think we _should_ get this error?

**Comment by niccokunzmann** [comment] 2024-05-20 05:57
It is nice if you are able to read the files. One could add general tolerance for tags that are specified to exist once but are duplicates.

**Comment by natashamm** [comment] 2024-05-20 23:25
I am having trouble reproducing the issue ... I wonder if this has already been fixed?

for reference I am using this .ics file with 2 method definitions:
```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:collective/icalendar
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-CALNAME:Holidays
X-WR-TIMEZONE:Etc/GMT
METHOD:PUBLISH
BEGIN:VEVENT
SUMMARY:New Year's Day
DTSTART:20220101
DTEND:20220101
DESCRIPTION:Happy New Year!
UID:636a0cc1dbd5a1667894465@icalendar
DTSTAMP:20221108T080105Z
STATUS:CONFIRMED
TRANSP:TRANSPARENT
SEQUENCE:0
END:VEVENT
END:VCALENDAR
```

```
with open(path) as f:
    calendar = Calendar.from_ical(f.read())
print(calendar)
print(Calendar(calendar))
```

```
VCALENDAR({'VERSION': vText('b'2.0''), 'PRODID': vText('b'collective/icalendar''), 'CALSCALE': vText('b'GREGORIAN''), 'METHOD': [vText('b'PUBLISH''), vText('b'PUBLISH'')], 'X-WR-CALNAME': vText('b'Holidays''), 'X-WR-TIMEZONE': vText('b'Etc/GMT'')}, VEVENT({'SUMMARY': vText('b"New Year's Day"'), 'DTSTART': vDDDTypes(2022-01-01, Parameters({})), 'DTEND': vDDDTypes(2022-01-01, Parameters({})), 'DESCRIPTION': vText('b'Happy New Year!''), 'UID': vText('b'636a0cc1dbd5a1667894465@icalendar''), 'DTSTAMP': vDDDTypes(2022-11-08 08:01:05+00:00, Parameters({})), 'STATUS': vText('b'CONFIRMED''), 'TRANSP': vText('b'TRANSPARENT''), 'SEQUENCE': 0}))
VCALENDAR({'VERSION': vText('b'2.0''), 'PRODID': vText('b'collective/icalendar''), 'CALSCALE': vText('b'GREGORIAN''), 'METHOD': [vText('b'PUBLISH''), vText('b'PUBLISH'')], 'X-WR-CALNAME': vText('b'Holidays''), 'X-WR-TIMEZONE': vText('b'Etc/GMT'')})
```

**Comment by niccokunzmann** [comment] 2024-05-21 08:42
Seeing that this is not an error and we cannot reproduce this with the latest version, I would close this. If this is a problem again, people can comment with the ICS file or open a new issue.

```
'METHOD': [vText('b'PUBLISH''), vText('b'PUBLISH'')],
```

Thanks @natashamm for researching!

**Closed by niccokunzmann** 2024-05-21 08:42 UTC
Labels: help wanted, good first issue
