### ISSUE TITLE
Document Page Still Broken

### ISSUE THREAD

**Issue by Aster-the-Med-Stu** [collective/icalendar#270] opened 2018-09-12 14:50 UTC
It is ~~8102~~ 2018 now and the doc page is still suffering from expired certificate of [cdnmedia.readthedocs.org](https://cdnmedia.readthedocs.org) . So js and css still not loads.

Edit: It is ~~9102~~ 2019 now....

**Comment by chrisconlan** [comment] 2018-10-01 18:11
Looks bad and make me not trust this otherwise helpful package. Please fix.

**Comment by Lx** [comment] 2019-06-10 07:01
For anyone wanting to view the docs properly, a workaround is to try to visit one of the affected resources directly:

https://cdnmedia.readthedocs.org/css/sphinx_rtd_theme.css

and "trust" or otherwise "authorise" that resource to be visited.  After this, the docs display correctly.

**Comment by RagingRoosevelt** [comment] 2020-03-02 23:45
Duplicate of #264

**Closed** 2022-09-05 09:55 UTC
