### ISSUE TITLE
Docs site is down? 

### ISSUE THREAD

**Issue by davidawad** [collective/icalendar#288] opened 2019-03-21 17:12 UTC
https://icalendar.readthedocs.io/en/latest/ 

It would seem that the docs website isn't loading CSS anymore because of a bad cert :(

**Comment by Lx** [comment] 2019-06-10 07:01
Duplicate of #270.

For anyone wanting to view the docs properly, a workaround is to try to visit one of the affected resources directly:

https://cdnmedia.readthedocs.org/css/sphinx_rtd_theme.css

and "trust" or otherwise "authorise" that resource to be visited.  After this, the docs display correctly.

**Comment by RagingRoosevelt** [comment] 2020-03-02 23:44
Duplicate of #264

**Comment by davidawad** [comment] 2020-03-12 20:22
Well I'm glad to hear that the issue has been reported twice before and still exists  😂

**Closed** 2022-09-05 09:39 UTC
