### ISSUE TITLE
CSS not loading on documentation

### ISSUE THREAD

**Issue by dullbananas** [collective/icalendar#302] opened 2020-02-02 16:36 UTC
When I try loading the readthedocs documentation for this, the css appears to be missing

**Comment by RagingRoosevelt** [comment] 2020-03-02 23:40
It seems like this is a SSL cert issue.  I tried to load some of the asset files and I get a `NET::ERR_CERT_DATE_INVALID` error (eg see [here](https://assets.readthedocs.org/static/javascript/underscore.js)).   If I load the link itself and then select "accept the risk" it will load and then so will the rest of the page.  But that doesn't seem like the correct fix.

**Comment by RagingRoosevelt** [comment] 2020-03-02 23:45
Duplicate of #264

**Closed** 2022-04-25 01:08 UTC
